import { SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } from 'discord.js';
import { isAdmin } from '../utils/adminCheck.js';

// ── Contenu des pages ─────────────────────────────────────────────────────────

export const GUIDE_PAGES = [

  // ─── PAGE 0 : /aide — Assistant ──────────────────────────────────────────
  {
    title: '❓ /aide — Assistant intégré',
    color: 0x5865f2,
    description: [
      '**Le bot inclut un assistant qui répond à tes questions en éphémère.**',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**💬 `/aide` — Poser une question**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/aide question:comment ajouter une base de données ?',
      '/aide question:comment configurer les embeds ?',
      '/aide question:créer un groupe sous-menu',
      '```',
      'Le bot répond instantanément avec des explications et exemples.',
      '',
      '**Sujets supportés :**',
      '• `base de données` `db` `json` `csv` `pdf` — Importer et configurer des bases',
      '• `embed` `apparence` `couleur` `image` — Personnaliser les embeds',
      '• `groupe` `sous-menu` — Organiser le menu',
      '• `option` `vip` `accès` — Gérer les options de recherche',
      '• `plugin` `api` `externe` — Connecter des APIs',
      '• `crédits` `plan` `vip` — Gérer les accès et plans',
      '• `logs` `historique` — Activer et consulter les logs',
      '• `blacklist` `bloquer` — Bloquer des membres',
      '• `config` `admin` `rôle` — Configuration générale',
      '• `bot` `owner` `statut` — Profil et ownership du bot',
      '• `search` `menu` `déployer` — Déployer le menu de recherche',
      '• `statut` `automatique` `rôle` — Détection de statut',
      '',
      '> 💡 Si ta question n\'est pas reconnue, essaie de reformuler avec des mots-clés.',
      '> 📖 Utilise ce guide pour des explications détaillées.',
      '',
      '**Limites :**',
      '• Répond à partir d\'une base de connaissances locale (pas d\'IA externe)',
      '• Ne gère pas les questions hors-sujet ou les configurations spécifiques à ton serveur',
      '• Pour les cas complexes → ce guide ou `/help categorie:...`',
    ].join('\n')
  },

  // ─── PAGE 1 : Démarrage ───────────────────────────────────────────────────
  {
    title: '🚀 Démarrage — Vue d\'ensemble & Ordre de setup',
    color: 0x5865f2,
    description: [
      '**Bienvenue dans le guide admin complet de NΞXUS™ S€archer.**',
      'Ce guide te donne toutes les infos pour configurer et utiliser le bot de A à Z.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📋 Ordre recommandé pour bien démarrer**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '',
      '**Étape 1 — Configurer le rôle admin**',
      '> `/config set cle:admin_role_id valeur:ID_DU_ROLE`',
      '> Sans ça, personne d\'autre que toi (owner) ne peut utiliser les commandes admin.',
      '',
      '**Étape 2 — Ajouter tes bases de données**',
      '> `/db add` → Upload un fichier .json/.csv/.zip etc.',
      '> C\'est le cœur du bot. Sans base, le bot n\'a rien à chercher.',
      '',
      '**Étape 3 — Définir les champs à afficher**',
      '> `/db fields` → Dis au bot quelles colonnes montrer dans les résultats.',
      '',
      '**Étape 4 — Personnaliser l\'apparence**',
      '> `/db config` → Couleur, titre, thumbnail de l\'embed résultats.',
      '> `/embed set` → Personnaliser le menu principal (affiché par /search).',
      '',
      '**Étape 5 — Organiser avec des groupes** *(optionnel)*',
      '> `/group create` → Crée des sous-menus pour regrouper tes options.',
      '',
      '**Étape 6 — Configurer les logs** *(recommandé)*',
      '> `/logs setup` → Choisir un salon pour recevoir un log de chaque recherche.',
      '',
      '**Étape 7 — Déployer le menu de recherche**',
      '> `/search` → Envoie l\'embed avec le bouton "Lancer une recherche" dans un salon.',
      '> Tes membres cliquent dessus et le menu apparaît en éphémère (privé).',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📌 Points importants à retenir**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '• Toutes les commandes admin sont **éphémères** (seul toi les vois).',
      '• Le menu de recherche est aussi **éphémère** pour les membres.',
      '• VIP = rôle Discord configuré via `/plan set` → accès aux bases/options VIP.',
      '• Les plugins permettent de connecter des APIs externes (IntelX, NazAPI…).',
      '',
      '> 📖 Navigue avec les boutons ◀ ▶ pour lire le guide complet.',
    ].join('\n')
  },

  // ─── PAGE 2 : /db — Importer des bases ───────────────────────────────────
  {
    title: '🗄️ /db — Ajouter & Gérer tes bases de données',
    color: 0x57f287,
    description: [
      '**Les bases de données sont les fichiers que le bot va chercher.**',
      'Il supporte : `.json` `.jsonl` `.csv` `.txt` `.zip` (contenant des json/csv).',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**➕ `/db add` — Ajouter une base**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/db add nom:sfr label:SFR fichier:[ton_fichier.json]',
      '        emoji:📱 description:Base opérateur SFR',
      '        vip:false options:email,phone id_externe:SFR_2024',
      '```',
      '• **`nom`** *(obligatoire)* — Identifiant interne, sans espaces, ex: `sfr` `bouygues`.',
      '• **`label`** — Nom affiché dans le menu, ex: `SFR`.',
      '• **`fichier`** — Le fichier à uploader directement dans Discord.',
      '• **`emoji`** — Emoji devant le nom dans le menu. Peut être un emoji custom `<:sfr:123456>`.',
      '• **`description`** — Texte court affiché sous le nom dans le menu.',
      '• **`vip`** — Si `true`, seuls les VIP (et admins) voient et utilisent cette base.',
      '• **`options`** — Options de recherche liées (ex: `email,phone`). Quand on cherche par email, cette base sera **prioritaire** dans les résultats.',
      '• **`id_externe`** — Référence personnelle libre (ex: `SFR_2024`) pour t\'organiser.',
      '',
      '> ⚠️ Le `nom` est permanent et sert de clé. Change le `label` si tu veux afficher un autre nom.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**✏️ `/db edit` — Modifier une base existante**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/db edit nom:sfr label:SFR Pro options:email,phone,name id_externe:SFR_V2',
      '```',
      'Modifie le label, description, emoji, options liées ou id_externe sans retoucher le fichier.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🗑️ `/db remove` — Supprimer une base**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/db remove nom:sfr',
      '```',
      '> ⚠️ **Irréversible.** Supprime la base ET son fichier de données.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📋 `/db list` — Voir toutes les bases**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      'Affiche : nom, label, emoji, accès (VIP/libre), visible dans le menu, nombre d\'entrées, options liées.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🔍 `/db info` — Détails complets d\'une base**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/db info nom:sfr',
      '```',
      'Affiche : tous les champs configurés, embed, accès, options liées, ID externe, chemin fichier.',
    ].join('\n')
  },

  // ─── PAGE 3 : /db — Config, Fields, Access, Menu ─────────────────────────
  {
    title: '🗄️ /db — Configurer l\'apparence & l\'accès',
    color: 0x57f287,
    description: [
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🎨 `/db config` — Personnaliser l\'embed des résultats**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/db config nom:sfr titre:📱 Résultats SFR couleur:ff6b35',
      '           thumbnail:https://... footer:Données SFR image:https://...',
      '```',
      'L\'embed résultats est ce qui s\'affiche quand un membre obtient des résultats de cette base.',
      '• **`titre`** — Titre de l\'embed. Supporte `{query}` (mot recherché) et `{results}` (nb résultats).',
      '• **`couleur`** — Code hex sans #, ex: `ff6b35` pour orange.',
      '• **`thumbnail`** — Petite image en haut à droite de l\'embed (URL directe).',
      '• **`image`** — Grande image en bas de l\'embed.',
      '• **`footer`** — Texte en bas de l\'embed.',
      '',
      '> 💡 Pour avoir "3 résultats pour jean@gmail.com" : `titre:{results} résultats pour {query}`',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📊 `/db fields` — Définir les colonnes affichées**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/db fields nom:sfr champs:👤:Prénom:prenom,📧:Email:email,📱:Tél:phone',
      '```',
      'Format de chaque champ : `emoji:Label:clé_json`',
      '• **`emoji`** — Affiché devant la valeur dans les résultats.',
      '• **`Label`** — Nom du champ affiché (ex: "Email").',
      '• **`clé_json`** — Le nom exact de la colonne dans ton fichier (ex: `email`, `phone_number`).',
      '',
      '> ⚠️ Si tu ne configures pas `/db fields`, le bot affiche TOUTES les colonnes brutes.',
      '> Utilise `/db info nom:sfr` pour voir les clés disponibles dans ton fichier.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🔒 `/db access` — Passer une base en VIP**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/db access nom:sfr mode:vip',
      '/db access nom:sfr mode:free',
      '```',
      '• `vip` → Seuls les membres avec le rôle VIP (ou admin) peuvent chercher dans cette base.',
      '• `free` → Accessible à tous.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**👁️ `/db menu` — Afficher/cacher du menu principal**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/db menu nom:sfr visible:false',
      '```',
      'Cacher une base du menu ne la supprime pas — elle reste cherchable via un groupe ou un plugin.',
      'Utile pour désactiver temporairement sans perdre la config.',
    ].join('\n')
  },

  // ─── PAGE 4 : /group ─────────────────────────────────────────────────────
  {
    title: '📂 /group — Créer des sous-menus dans le menu principal',
    color: 0xfee75c,
    description: [
      '**Les groupes permettent d\'organiser le menu principal en sous-menus.**',
      'Ex: un groupe "Opérateurs" qui contient SFR, Bouygues, Orange…',
      'Quand un membre clique sur le groupe, un sous-menu apparaît avec ses éléments.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**➕ `/group create` — Créer un groupe**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/group create valeur:operateurs label:Opérateurs emoji:📱 description:Bases opérateurs FR',
      '```',
      '• **`valeur`** *(obligatoire)* — Identifiant interne sans espaces, ex: `operateurs`.',
      '• **`label`** — Nom affiché dans le menu principal.',
      '• **`emoji`** — Emoji devant le groupe.',
      '• **`description`** — Texte sous le nom dans le menu.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**➕ `/group add` — Ajouter un élément dans le groupe**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/group add groupe:operateurs cible:db_sfr label:SFR emoji:📱',
      '/group add groupe:operateurs cible:email label:Par Email emoji:📧',
      '/group add groupe:operateurs cible:custom_steam label:Steam emoji:🎮',
      '```',
      '• **`groupe`** — Valeur du groupe créé avec `/group create`.',
      '• **`cible`** — Ce que déclenche l\'élément :',
      '  - `db_NOM` → Ouvre la recherche dans la base `NOM` (ex: `db_sfr`)',
      '  - `email`, `phone`, `name`… → Option de recherche intégrée',
      '  - `custom_VALEUR` → Option personnalisée',
      '• **`label`** — Nom de l\'élément dans le sous-menu.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🎨 `/group config` — Personnaliser l\'embed du sous-menu**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/group config valeur:operateurs titre:📱 Opérateurs FR couleur:5865f2 thumbnail:https://...',
      '```',
      'Personnalise l\'embed affiché quand le membre ouvre le sous-menu du groupe.',
      '',
      '> 💡 Tu peux aussi faire `/embed group groupe:operateurs` pour plus d\'options (footer, image).',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**Autres commandes /group**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '• `/group set-emoji valeur:X emoji:📱` → Changer l\'emoji du **groupe** dans le menu principal.',
      '• `/group emoji groupe:X cible:db_sfr emoji:📱` → Changer l\'emoji d\'un **élément** dans le sous-menu.',
      '• `/group remove-item groupe:X cible:db_sfr` → Retirer un élément du groupe.',
      '• `/group delete valeur:X` → Supprimer entièrement le groupe *(irréversible)*.',
      '• `/group list` → Voir tous les groupes et leurs éléments.',
      '',
      '> ⚠️ Un groupe doit contenir au moins un élément pour apparaître dans le menu.',
      '> Le sous-menu inclut toujours une option **Global** en premier (recherche dans tout le groupe).',
    ].join('\n')
  },

  // ─── PAGE 5 : /option ────────────────────────────────────────────────────
  {
    title: '⚙️ /option — Gérer les options de recherche',
    color: 0xeb459e,
    description: [
      '**Les options sont les types de recherche disponibles dans le menu.**',
      'Il y a 3 types :',
      '• **Intégrées** — email, phone, name, username, discord_id, ip, city, postal, address, iban, password, intelx, nazapi.',
      '• **Personnalisées** — créées par toi avec `/option add`.',
      '• **Bases de données** — apparaissent automatiquement si visibles dans le menu.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**➕ `/option add` — Ajouter une option personnalisée**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/option add label:Steam ID emoji:🎮 description:Recherche par Steam ID',
      '           modal_label:Entrez votre Steam ID vip_only:false',
      '```',
      '• **`label`** — Nom affiché dans le menu (ex: "Steam ID").',
      '• **`emoji`** — Emoji devant l\'option.',
      '• **`description`** — Texte sous le nom dans le menu.',
      '• **`modal_label`** — Texte affiché dans la boîte de saisie quand le membre clique.',
      '• **`vip_only`** — Si `true`, réservé aux VIP.',
      '',
      '> 💡 L\'option crée un type de recherche. Pour que ça retourne des résultats, associe un **plugin** ou une **base** à cette option.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🗑️ `/option remove` — Masquer ou supprimer une option**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/option remove label:Email',
      '/option remove label:Steam ID',
      '```',
      '• Option **intégrée** → Elle est **masquée** du menu (pas supprimée). Utilise `/option restore` pour la réafficher.',
      '• Option **personnalisée** → Elle est **supprimée définitivement**.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🔒 `/option access` — Passer une option en VIP**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/option access option:email mode:vip',
      '/option access-bulk mode:vip',
      '/option access-credits nombre:3',
      '```',
      '• `/option access` → Passe UNE option en VIP ou libre.',
      '• `/option access-bulk` → Passe TOUTES les options en VIP ou libre d\'un coup.',
      '• `/option access-credits` → Définit combien de recherches/jour les non-VIP ont (défaut: 5).',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**Autres commandes /option**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '• `/option list` → Voir toutes les options (intégrées, custom, masquées, VIP).',
      '• `/option edit label:X new_label:Y` → Modifier une option custom.',
      '• `/option restore label:Email` → Réafficher une option intégrée masquée.',
      '• `/option emoji option:email nouvel_emoji:📧` → Changer l\'emoji d\'une option intégrée.',
      '• `/option emoji-list` → Voir tous les emojis actuels.',
      '• `/option emoji-reset` → Remettre les emojis par défaut.',
      '• `/option access-list` → Voir quel accès est configuré pour chaque option.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🆔 `/option ids` — Voir tous les identifiants**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/option ids',
      '```',
      'Affiche la liste complète de tous les IDs réutilisables dans les autres commandes :',
      '• **Options intégrées** → `email`, `phone`, `name`, `username`, `discord_id`, `ip`, `address`, `iban`, `password`, `intelx`, `nazapi`',
      '• **Options personnalisées** → leur `valeur` interne (ex: `steam_id`)',
      '• **Groupes** → leur `valeur` (ex: `operateurs`) pour `/embed group groupe:`, `/group config valeur:`',
      '• **Bases de données** → leur `nom` préfixé `db_` (ex: `db_sfr`) pour `/group add cible:`',
      '',
      '> 💡 Utilise `/option ids` avant de configurer `/plugin add option:`, `/db edit options:`, ou `/group add cible:` pour ne jamais te tromper d\'identifiant.',
    ].join('\n')
  },

  // ─── PAGE 6 : /embed ─────────────────────────────────────────────────────
  {
    title: '🎨 /embed — Personnaliser l\'apparence des embeds',
    color: 0xf1c40f,
    description: [
      '**Il y a 3 types d\'embeds configurables :**',
      '1. L\'embed du **menu principal** (affiché par `/search`)',
      '2. L\'embed des **résultats par option** (email, phone, etc.)',
      '3. L\'embed des **sous-menus de groupe**',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**1. Embed du menu principal — `/embed set`**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/embed set title:🔍 NΞXUS Searcher color:#5865f2',
      '           footer:NΞXUS™ footer_icon:https://... thumbnail_fichier:[image.png]',
      '```',
      'C\'est l\'embed statique affiché quand tu fais `/search` dans un salon.',
      '**Options disponibles :**',
      '• `title` `description` `color` `footer` — champs texte classiques.',
      '• `footer_icon` — URL de l\'icône à gauche du texte du footer.',
      '• `thumbnail` / `image` — URL directe vers une image.',
      '• `thumbnail_fichier` / `image_fichier` / `footer_icon_fichier` — **upload directement depuis ta galerie** (glisse-dépose ton image dans Discord).',
      '',
      '> 💡 Les champs sont **tous optionnels** : ne renseigne que ce que tu veux modifier.',
      '> `/embed preview` → Prévisualiser l\'embed actuel.',
      '> `/embed reset` → Remettre l\'embed par défaut.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**2. Embed des résultats — `/embed option`**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/embed option option:email titre:📧 Résultats Email description:{results} résultats pour {query}',
      '              couleur:5865f2 footer:NΞXUS™ footer_icon:https://... thumbnail_fichier:[img.png]',
      '```',
      '**Variables disponibles dans titre, description, footer :**',
      '• `{query}` → La valeur recherchée (ex: `jean@gmail.com`)',
      '• `{type}` → Le type de recherche (ex: `email`)',
      '• `{results}` → Le nombre de résultats trouvés',
      '• `{user}` → Le pseudo Discord du membre qui cherche',
      '',
      '> 💡 Images : utilise `thumbnail_fichier` / `image_fichier` / `footer_icon_fichier` pour uploader depuis ta galerie sans lien.',
      '> ⚠️ Appelle `/embed option` **sans arguments** pour voir le guide des variables.',
      '',
      '• `/embed option-view option:email` → Voir la configuration actuelle d\'une option.',
      '• `/embed option-reset option:email` → Remettre à zéro l\'embed d\'une option.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**3. Embed des groupes — `/embed group`**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/embed group groupe:operateurs titre:📱 Opérateurs FR couleur:5865f2',
      '              thumbnail_fichier:[logo.png] footer:NΞXUS™ footer_icon_fichier:[icon.png]',
      '```',
      'Personnalise l\'embed affiché quand un membre ouvre le sous-menu d\'un groupe.',
      'Supporte les mêmes options que `/embed set` (URL + fichier galerie + footer_icon).',
      '• `/embed group-reset groupe:operateurs` → Remettre à zéro l\'embed d\'un groupe.',
    ].join('\n')
  },

  // ─── PAGE 7 : /tool ──────────────────────────────────────────────────────
  {
    title: '🔧 /tool — Moteur de tools externes (OSINT avancé)',
    color: 0x00b4d8,
    description: [
      '**`/tool` permet d\'intégrer des outils OSINT externes directement dans le bot.**',
      'Le bot analyse le dépôt GitHub, génère un module JS natif, et l\'exécute en parallèle',
      'avec les bases de données à chaque recherche. Résultats affichés dans les embeds.',
      '',
      '> ⚠️ **Réservé aux owners du bot** (`/owner list` pour voir qui est owner).',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**➕ `/tool add` — Intégrer un outil depuis GitHub**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/tool add url:https://github.com/sherlock-project/sherlock',
      '/tool add url:https://github.com/megadose/holehe',
      '```',
      'Le bot analyse automatiquement le dépôt, détecte son type (username/email checker…)',
      'et génère un module JS natif dans `data/tools/`. **Aucune exécution Python.**',
      '',
      '**Types de tools supportés :**',
      '• `username` — Vérifie si un pseudo existe sur 15+ plateformes (Twitter, GitHub, Reddit…)',
      '• `email` — Vérifie si un email est enregistré sur des services courants',
      '• `api` — Appelle une API externe HTTP directement',
      '• `scraper` — Scraping web natif',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📋 Autres commandes /tool**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '• `/tool list` → Voir tous les tools installés (ID, type, statut actif/inactif)',
      '• `/tool test id:<id> query:<requête>` → Tester un tool en live',
      '• `/tool config id:<id> key:<clé_api>` → Configurer la clé API d\'un tool',
      '• `/tool toggle id:<id>` → Activer / désactiver un tool sans le supprimer',
      '• `/tool link id:<id> option:<option>` → Lier un tool à une option de recherche spécifique',
      '• `/tool delete id:<id>` → Supprimer un tool définitivement',
      '• `/tool cache` → Vider le cache des résultats (10 min par défaut)',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**⚡ Cache & Détection automatique**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '• Les résultats sont mis en cache **10 minutes** — indiqué par ⚡ dans l\'embed.',
      '• Le bot **détecte automatiquement** le type de la requête (email, IP, username, nom…)',
      '  et sélectionne les tools pertinents sans configuration manuelle.',
      '• Les tools s\'exécutent **en parallèle** avec les recherches en base de données.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📌 Différence /plugin vs /tool**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '• `/plugin` → Tu uploads ton propre fichier `.js` (plugin manuel)',
      '• `/tool` → Le bot génère automatiquement le module depuis GitHub (zéro code)',
    ].join('\n')
  },

  // ─── PAGE 8 : /plugin ────────────────────────────────────────────────────
  {
    title: '🔌 /plugin — Connecter des APIs externes',
    color: 0xe67e22,
    description: [
      '**Les plugins permettent de connecter des APIs externes au bot.**',
      'Ex: IntelX, NazAPI, Shodan, ou toute API personnalisée.',
      'Chaque plugin est un fichier `.js` uploadé qui est appelé à chaque recherche.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**➕ `/plugin add` — Ajouter un plugin**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/plugin add nom:INTELX_API fichier:[plugin_intelx.js]',
      '           option:intelx description:Plugin Intel_X vip:true',
      '```',
      '• **`nom`** — Identifiant unique du plugin.',
      '• **`fichier`** — Le fichier .js à uploader.',
      '• **`option`** — L\'option de recherche qui déclenche ce plugin (ex: `intelx`, `email`, `custom_steam`).',
      '• **`vip`** — Si `true`, réservé aux VIP.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📄 Format du fichier plugin**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```js',
      'export async function search(query, type) {',
      '  // query = ce que le membre a tapé',
      '  // type  = le type d\'option (email, intelx, custom_steam…)',
      '  const data = await fetch(`https://api.exemple.com/search?q=${query}`);',
      '  const json = await data.json();',
      '  return {',
      '    results: json.items,   // tableau de résultats',
      '    total:   json.count    // nombre total',
      '  };',
      '}',
      '```',
      '> 💡 Utilise `/plugin help` pour voir le format complet attendu.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**Autres commandes /plugin**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '• `/plugin list` → Voir tous les plugins (`🟢` chargé / `🔴` erreur).',
      '• `/plugin reload nom:INTELX_API` → Recharger un plugin sans redémarrer le bot.',
      '  → **À faire après chaque modification de ton fichier plugin.**',
      '• `/plugin remove nom:INTELX_API` → Supprimer un plugin.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**⚠️ Limites et conseils**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '• Un plugin doit **exporter une fonction `search`** en ES Module (`export async function`).',
      '• Si une API nécessite une clé API, mets-la directement dans le fichier plugin (ou utilise les variables d\'environnement).',
      '• Si le plugin plante, le bot affiche une erreur à l\'utilisateur — vérifie `/plugin list` pour voir l\'état.',
      '• Un seul plugin peut être associé à une option. Si tu as plusieurs sources, fais-les chercher dans la même fonction.',
    ].join('\n')
  },

  // ─── PAGE 8 : /logs ──────────────────────────────────────────────────────
  {
    title: '📋 /logs — Surveiller & Analyser les recherches',
    color: 0x9b59b6,
    description: [
      '**Les logs enregistrent chaque recherche effectuée dans le bot.**',
      'Ils permettent de surveiller l\'utilisation, détecter les abus et analyser les tendances.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🔧 `/logs setup` — Activer les logs**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/logs setup salon:#logs-recherches',
      '```',
      'Active l\'envoi d\'un embed dans le salon choisi à chaque recherche.',
      'L\'embed contient : utilisateur, type d\'option, requête, nombre de résultats, heure.',
      '',
      '> ⚠️ Le bot doit avoir la permission **Envoyer des messages** dans ce salon.',
      '',
      '• `/logs disable` → Désactiver les logs (les données en DB sont conservées).',
      '• `/logs status` → Voir si les logs sont actifs et dans quel salon.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📜 `/logs history` — Voir les dernières recherches**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/logs history nombre:20 utilisateur:@Dupont',
      '```',
      '• **`nombre`** — Nombre de résultats à afficher (défaut: 10, max: 50).',
      '• **`utilisateur`** *(optionnel)* — Filtrer par utilisateur spécifique.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🔎 `/logs search` — Recherche avancée dans les logs**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/logs search mot_cle:gmail.com utilisateur:@Dupont option:email',
      '            depuis:2025-01-01 jusqua:2025-12-31 limite:20',
      '```',
      '**Filtres disponibles (tous optionnels) :**',
      '• **`mot_cle`** — Cherche ce texte dans les requêtes enregistrées.',
      '• **`utilisateur`** — Filtrer par membre Discord.',
      '• **`option`** — Filtrer par type de recherche (`email`, `phone`, `db_sfr`…).',
      '• **`depuis`** — Date de début au format `YYYY-MM-DD`.',
      '• **`jusqua`** — Date de fin au format `YYYY-MM-DD`.',
      '• **`limite`** — Nombre max de résultats (défaut: 10).',
      '',
      '> 💡 Exemple : trouver tous les membres qui ont cherché une adresse gmail → `mot_cle:gmail.com`',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**👤 `/logs user-history` — Historique paginé d\'un membre**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/logs user-history utilisateur:@Dupont',
      '```',
      '• Envoie un embed éphémère avec **1 recherche par page**.',
      '• Titre : **Historique de [Dupont] • 1/200** (page actuelle / total).',
      '• Chaque page affiche : option, requête, résultats, salon, date.',
      '• Boutons ◀ **Précédent** / **Suivant** ▶ pour naviguer.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🗑️ `/logs clear` — Supprimer tous les logs**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/logs clear',
      '```',
      '> ⚠️ **Irréversible.** Supprime tous les logs de la base de données.',
      '> N\'affecte pas les messages déjà envoyés dans le salon de logs Discord.',
    ].join('\n')
  },

  // ─── PAGE 9 : /credits & /plan ───────────────────────────────────────────
  {
    title: '💳 /credits & /plan — Gérer les accès, Plans & Abonnements',
    color: 0x2ecc71,
    description: [
      '**Le système de crédits limite le nombre de recherches par jour pour les non-VIP.**',
      'Les plans associent un rôle Discord à un niveau d\'accès. Un plan peut avoir une **durée d\'abonnement** avec expiration automatique.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📋 `/plan set` — Créer un plan pour un rôle**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/plan set role:@VIP nom:VIP credits:100 illimite:true',
      '/plan set role:@Premium nom:Premium credits:50 duree:30',
      '/plan set role:@Trial nom:Trial credits:10 duree:7',
      '```',
      '• **`role`** — Le rôle Discord concerné (mention ou ID).',
      '• **`nom`** — Nom du plan (affiché dans `/credits info`).',
      '• **`credits`** — Nombre de recherches/jour pour ce plan.',
      '• **`illimite`** — Si `true`, pas de limite de recherches.',
      '• **`duree`** *(facultatif)* — Durée en jours avant expiration automatique. Sans durée = plan permanent.',
      '',
      '> 💡 **Ordre recommandé :** crée les plans avant de configurer les options VIP.',
      '> Un membre avec le rôle @VIP aura automatiquement son plan appliqué.',
      '',
      '• `/plan list` → Voir tous les plans (inclut toujours le **plan de base** et la durée si définie).',
      '  - Système statut **désactivé** : affiche "Plan gratuit — pour tout le monde".',
      '  - Système statut **activé** : affiche "Plan statut — nécessite le rôle attribution auto".',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**▶️ `/plan apply` — Appliquer un plan manuellement**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/plan apply user:@Dupont role:@Premium',
      '```',
      '• Attribue le rôle au membre automatiquement.',
      '• Si le plan a une durée → crée le **timer d\'abonnement** et envoie un **DM de confirmation** avec la date d\'expiration.',
      '• Si le plan est permanent → applique les crédits sans timer.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**⏱️ Système d\'abonnement & Expiration automatique**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      'Quand un plan a une durée, le bot gère tout automatiquement :',
      '',
      '**Rappels DM envoyés à l\'utilisateur :**',
      '• 🟡 **1 jour avant** l\'expiration → DM de rappel',
      '• 🔴 **5 minutes avant** l\'expiration → DM d\'avertissement urgent',
      '• ❌ **À l\'expiration** → DM de confirmation + retrait du plan',
      '',
      '**À l\'expiration :**',
      '• Le **rôle** est retiré automatiquement.',
      '• Le **plan** est remis à zéro :',
      '  - Système statut **désactivé** → plan gratuit (crédits par défaut)',
      '  - Système statut **activé** → aucun plan (accès bloqué jusqu\'au renouvellement)',
      '',
      '**Commandes de gestion :**',
      '```',
      '/plan subs user:@Dupont',
      '/plan revoke user:@Dupont role:@Premium',
      '```',
      '• **`/plan subs`** — Voir les abonnements actifs d\'un utilisateur (date d\'expiration, rappels envoyés).',
      '• **`/plan revoke`** — Révoquer manuellement un abonnement avant expiration (retire rôle + plan + DM à l\'utilisateur).',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**💰 Commandes `/credits`**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/credits add user:@Dupont montant:10',
      '/credits unlimited user:@Dupont',
      '/credits reset user:@Dupont',
      '/credits info user:@Dupont',
      '```',
      '• **`credits add`** — Donne des crédits supplémentaires à un utilisateur (s\'ajoutent à son plan).',
      '• **`credits unlimited`** — Donne un accès illimité à un utilisateur spécifique (bypasse son plan).',
      '• **`credits reset`** — Remet l\'utilisateur sur son plan par défaut (retire les bonus).',
      '• **`credits info`** — Voir : plan actuel, crédits restants, prochain rechargement.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**⚙️ Configurer le quota gratuit**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/option access-credits nombre:5',
      '```',
      'Définit combien de recherches/jour ont les membres sans aucun plan (plan gratuit).',
      'Par défaut : **5 recherches/jour**. Se recharge automatiquement à minuit.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📌 Fonctionnement résumé**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '1. Membre sans rôle VIP → **Plan gratuit** (X recherches/jour).',
      '2. Membre avec rôle @VIP → **Plan VIP** (crédits ou illimité selon config).',
      '3. Plan avec durée → **Expiration automatique** + rappels DM.',
      '4. Admin → **Toujours illimité**, bypass tout.',
      '5. Blacklisté → **Accès refusé** peu importe le plan.',
    ].join('\n')
  },

  // ─── PAGE 10 : /blacklist, /config, /stats ───────────────────────────────
  {
    title: '🚫 /blacklist • ⚙️ /config • 📊 /stats',
    color: 0xe74c3c,
    description: [
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🚫 /blacklist — Bloquer des utilisateurs**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/blacklist add user:@Dupont raison:Abus du système',
      '/blacklist remove user:@Dupont',
      '/blacklist list',
      '```',
      '• **`add`** — Bloque un membre. Il verra "🚫 Tu as été blacklisté" à chaque tentative de recherche.',
      '• **`remove`** — Retire le membre de la blacklist. Accès immédiatement restauré.',
      '• **`list`** — Voir tous les membres bloqués avec la raison et la date.',
      '',
      '> ⚠️ La blacklist agit sur l\'ID Discord, pas le pseudo. Renommer ne contourne pas le blocage.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**⚙️ /config — Configuration générale du bot**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/config set cle:admin_role_id valeur:1234567890123456789',
      '/config show',
      '```',
      '**Clés de configuration disponibles :**',
      '• `admin_role_id` → ID du rôle Discord qui a accès aux commandes admin.',
      '  → **À configurer en priorité.** Sans ça, seul le propriétaire du serveur est admin.',
      '• `vip_role_id` → ID du rôle VIP (accès aux options/bases VIP).',
      '',
      '**Comment trouver l\'ID d\'un rôle ?**',
      '> Mode développeur Discord (Paramètres → Avancé → Mode développeur)',
      '> Puis clic droit sur le rôle → Copier l\'ID.',
      '',
      '• `/config show` → Voir toutes les configurations actuelles.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📊 /stats — Statistiques du bot**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/stats',
      '```',
      'Affiche un résumé complet :',
      '• Nombre total de recherches effectuées.',
      '• Nombre d\'utilisateurs enregistrés.',
      '• Nombre de bases de données et leurs tailles.',
      '• Nombre de plugins chargés.',
      '• Uptime du bot.',
      '• Top recherches et utilisateurs les plus actifs.',
    ].join('\n')
  },

  // ─── PAGE 11 : /bot & /search ────────────────────────────────────────────
  {
    title: '🤖 /bot — Profil du bot • 🔍 /search — Déployer le menu',
    color: 0x3498db,
    description: [
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🤖 /bot — Modifier le profil du bot**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '',
      '**`/bot rename`** — Changer le nom du bot',
      '```',
      '/bot rename nom:NΞXUS™',
      '```',
      '> ⚠️ **Limite Discord : 2 changements de nom par heure.** Au-delà, Discord bloque pendant 1h.',
      '',
      '**`/bot status`** — Modifier la présence et l\'activité',
      '```',
      '/bot status presence:online type:Watching texte:les données...',
      '/bot status presence:dnd type:Playing texte:NΞXUS™ Searcher',
      '```',
      '• **`presence`** : `online` (vert) / `idle` (jaune) / `dnd` (rouge) / `invisible` (gris).',
      '• **`type`** : `Playing` / `Watching` / `Listening` / `Competing`.',
      '• **`texte`** : Le texte affiché après le type (ex: "Regarde les données...").',
      '',
      '**`/bot bio`** — Modifier la bio du profil',
      '```',
      '/bot bio texte:Bot de recherche OSINT — NΞXUS™',
      '```',
      '> ⚠️ La bio est visible sur le profil public du bot. Max 190 caractères.',
      '',
      '**`/bot info`** — Voir les infos actuelles',
      '```',
      '/bot info',
      '```',
      'Affiche : nom du bot, ID, ping API, présence actuelle, activité, uptime.',
      '',
      '**`/bot reload`** — Redémarrer le bot',
      '```',
      '/bot reload',
      '```',
      'Redémarre proprement le processus du bot. Il revient automatiquement en quelques secondes.',
      'Utile après une modification de config, pour recharger les plugins, ou en cas de comportement anormal.',
      '> ⚠️ Il y aura une brève coupure (2-5 sec) pendant le redémarrage.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**👑 Owners du bot — `/owner`**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '> ⚠️ Toutes les commandes `/bot` nécessitent d\'être **owner** du bot.',
      '> L\'owner principal est configuré en dur dans le code (ID fixe).',
      '',
      '```',
      '/owner add utilisateur:@Dupont    → Ajouter un owner',
      '/owner remove utilisateur:@Dupont → Retirer un owner',
      '/owner list                       → Voir tous les owners',
      '```',
      '• Un owner a accès à `/bot` et à `/owner`.',
      '• L\'owner principal ne peut pas être retiré.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🔍 /search — Déployer le menu de recherche**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/search deploy',
      '```',
      'Envoie l\'embed de recherche dans le salon **courant** avec un bouton "Lancer une recherche".',
      '',
      '**Fonctionnement pour les membres :**',
      '1. Le membre clique sur le bouton → Un menu déroulant apparaît **(éphémère, privé)**.',
      '2. Il choisit Global / un groupe / une base / une option.',
      '3. Une boîte de saisie (modal) apparaît pour entrer sa recherche.',
      '4. Les résultats s\'affichent en éphémère.',
      '',
      '**Embed d\'info public :**',
      '`/search info` → Affiche un embed d\'information dans le salon **(visible par tous)**.',
      '`/search info-set title:... description:... image_fichier:[img]` → Modifier cet embed.',
      'Cet embed n\'a pas de bouton — il sert à présenter le service aux membres.',
      '',
      '> 💡 Tu peux faire `/search deploy` dans plusieurs salons différents.',
      '> 💡 Personnalise l\'embed principal via `/embed set` et l\'embed info via `/search info-set`.',
      '',
    ].join('\n')
  },

  // ─── PAGE 13 : /statut-accès ─────────────────────────────────────────────
  {
    title: '🔄 /statut-accès — Attribution automatique de rôle',
    color: 0x1abc9c,
    description: [
      '**Le bot peut surveiller le statut personnalisé des membres et leur attribuer un rôle automatiquement.**',
      'Ex : si un membre met "NΞXUS" dans son statut, il reçoit automatiquement le rôle VIP.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**⚙️ `/statut-accès config` — Configurer la détection**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/statut-accès config role:@VIP texte:NΞXUS',
      '```',
      '• **`role`** — Le rôle Discord à attribuer automatiquement.',
      '• **`texte`** — Le texte à détecter dans le statut personnalisé du membre.',
      '',
      '**Fonctionnement :**',
      '1. Le bot vérifie les statuts de tous les membres toutes les 60 secondes.',
      '2. Si un membre a le texte configuré dans son statut → **le bot lui donne le rôle**.',
      '3. Si le texte disparaît de son statut → **le bot lui retire le rôle**.',
      '',
      '> ⚠️ **Prérequis :**',
      '> • Le bot doit avoir l\'intent "Presence" activé dans le portail développeur Discord.',
      '> • Le rôle du bot doit être **au-dessus** du rôle à attribuer dans la hiérarchie.',
      '> • Le bot doit avoir la permission **Gérer les rôles**.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**ℹ️ `/statut-accès info` — Voir la config actuelle**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/statut-accès info',
      '```',
      'Affiche : texte surveillé, rôle attribué, et si la détection est active.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🔴 `/statut-accès disable` — Désactiver**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/statut-accès disable',
      '```',
      'Désactive la détection. Le bot ne surveillera plus les statuts.',
      '> Les rôles déjà attribués ne sont PAS retirés automatiquement lors de la désactivation.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📋 `/statut-accès logs-set` / `logs-remove` — Logs d\'attribution**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/statut-accès logs-set salon:#logs-statut',
      '/statut-accès logs-remove',
      '```',
      'Envoie un log dans le salon choisi chaque fois qu\'un rôle est donné ou retiré.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🔒 Effet sur les recherches (Blocage d\'accès)**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      'Quand le système statut est **activé**, les membres **sans le rôle** ne peuvent faire **aucune recherche**.',
      'Dès qu\'ils cliquent sur le bouton Rechercher, ils reçoivent un embed éphémère :',
      '```',
      '🔒 Accès refusé',
      'Tu n\'as pas accès aux recherches.',
      'Pour obtenir l\'accès : ajoute "[texte configuré]" dans ton statut personnalisé Discord.',
      'Le rôle te sera attribué automatiquement une fois le statut détecté.',
      '```',
      '> ℹ️ Quand le système est **désactivé**, tout le monde a accès (plan gratuit normal).',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**💡 Cas d\'usage typique**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '> Configure un texte unique à ton service (ex: le nom de ton bot ou serveur).',
      '> Les membres qui mettent ce texte dans leur statut reçoivent automatiquement l\'accès VIP.',
      '> Utile pour récompenser les membres qui font de la publicité pour ton serveur.',
    ].join('\n')
  },

  // ─── PAGE 14 : /search nouvelles commandes ────────────────────────────────
  {
    title: '🔍 /search — Panneau de recherche & personnalisation',
    color: 0x5865f2,
    description: [
      '**Toutes les commandes `/search` pour gérer le panneau de recherche et le personnaliser.**',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📡 `/search deploy` — Déployer le panneau**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/search deploy',
      '```',
      'Envoie l\'embed principal avec les 3 boutons dans le salon courant :',
      '• <:rechercher:1511875326655856660> **Rechercher** — ouvre le menu de recherche',
      '• 👤 **Profil** — affiche le profil/crédits du membre',
      '• 📖 **Guide** — affiche le guide d\'utilisation (éphémère)',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🔒 `/search lock` / `unlock` — Verrouiller le panneau**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/search lock    → Verrouille le panneau (réservé owners)',
      '/search unlock  → Déverrouille le panneau',
      '```',
      'Quand le panneau est verrouillé, les membres voient un embed "🔒 Panel verrouillé".',
      'Pas de changement visuel sur les boutons — seulement un message éphémère à l\'utilisation.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🖱️ `/search btn-search` / `btn-profile` / `btn-guide` — Personnaliser les boutons**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/search btn-search label:Rechercher emoji:<:rechercher:1511875326655856660>',
      '/search btn-profile label:Mon Profil emoji:👤',
      '/search btn-guide   label:Guide emoji:<a:ZippyRiri_Utility:...>',
      '```',
      'Modifie le label et/ou l\'emoji de chaque bouton dans l\'embed principal.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**👤 `/search profile-set` — Configurer l\'embed de profil**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/search profile-set title:Ton profil description:... footer:... color:#5865f2',
      '```',
      '**Variables disponibles dans le texte :**',
      '• `{user}` — pseudo Discord',
      '• `{plan}` — nom du plan actuel',
      '• `{credits}` — crédits restants',
      '• `{max_credits}` — max crédits/jour',
      '• `{next_reset}` — prochain rechargement',
      '• `{searches}` — total recherches effectuées',
      '• `{unlimited}` — "♾️" si illimité, vide sinon',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📖 `/search guide-set` — Configurer l\'embed de guide**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/search guide-set title:Guide description:... footer:... color:#3b3b44',
      '```',
      'Modifie le guide affiché quand un membre clique sur le bouton Guide.',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**📋 `/logs-bot config` / `remove` — Logs des actions admin**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '```',
      '/logs-bot config salon:#logs-admin',
      '/logs-bot remove',
      '```',
      'Enregistre toutes les actions admin dans un salon (excl. /guide /help /aide /statut-logs /search-logs).',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      '**🎉 Tu as terminé le guide !**',
      '━━━━━━━━━━━━━━━━━━━━━━━',
      'Utilise `/help` pour un rappel rapide des commandes.',
      'Utilise `/guide` pour revenir à ce guide détaillé.',
      'Utilise `/aide question:...` pour obtenir une réponse rapide sur n\'importe quel sujet.',
      '',
      '> Si tu as des questions ou souhaites ajouter des fonctionnalités, contacte l\'équipe de développement.',
    ].join('\n')
  },
];

// ── Constructeurs d'embed/boutons ─────────────────────────────────────────────

export function buildGuideEmbed(page) {
  const p = GUIDE_PAGES[page];
  return new EmbedBuilder()
    .setColor(p.color)
    .setTitle(p.title)
    .setDescription(p.description.substring(0, 4090))
    .setFooter({ text: `NΞXUS™ Guide Admin • Page ${page + 1} sur ${GUIDE_PAGES.length} • Utilise les boutons pour naviguer` })
    .setTimestamp();
}

export function buildGuideRow(page) {
  const total = GUIDE_PAGES.length;
  return new ActionRowBuilder().addComponents(
    new ButtonBuilder()
      .setCustomId(`guide_prev_${page}`)
      .setLabel('◀ Précédent')
      .setStyle(ButtonStyle.Secondary)
      .setDisabled(page <= 0),
    new ButtonBuilder()
      .setCustomId(`guide_page_${page}`)
      .setLabel(`${page + 1} / ${total}`)
      .setStyle(ButtonStyle.Primary)
      .setDisabled(true),
    new ButtonBuilder()
      .setCustomId(`guide_next_${page}`)
      .setLabel('Suivant ▶')
      .setStyle(ButtonStyle.Secondary)
      .setDisabled(page >= total - 1)
  );
}

// ── Commande slash ────────────────────────────────────────────────────────────

export const data = new SlashCommandBuilder()
  .setName('guide')
  .setDescription('[ADMIN] Guide complet d\'utilisation du bot — toutes les commandes en détail avec un système de pages');

export async function execute(interaction) {
  if (!isAdmin(interaction.member)) {
    return interaction.reply({ content: '❌ Ce guide est réservé aux administrateurs.', ephemeral: true });
  }

  return interaction.reply({
    embeds: [buildGuideEmbed(0)],
    components: [buildGuideRow(0)],
    ephemeral: true
  });
}
